CREATE DATABASE BTL

USE BTL

CREATE TABLE HANGHOA
(
	MaHH CHAR(20) CONSTRAINT PK_HANGHOA PRIMARY KEY,
	TenHH NVARCHAR(30) NOT NULL,
	DVT NVARCHAR(20) NOT NULL,
	DGN FLOAT CONSTRAINT CK_DGN CHECK(DGN > 0),
	DGB FLOAT CONSTRAINT CK_DGB CHECK(DGB > 0),
	MaKH CHAR(20) NOT NULL,
	MaDM CHAR(20) NOT NULL
);

CREATE TABLE NHAPHANPHOI
(
	MaNPP CHAR(20) CONSTRAINT PK_NHAPHANPHOI PRIMARY KEY,
	TenNPP NVARCHAR(30) NOT NULL,
	DiaChiNPP NVARCHAR(30) NOT NULL,
	SDTNPP CHAR(10) CONSTRAINT CK_SDTNPP CHECK(LEN(SDTNPP) = 10 AND ISNUMERIC(SDTNPP) = 1)
);

CREATE TABLE NGUOINHANHANG
(
	MaNNH CHAR(20) CONSTRAINT PK_NGUOINHANHANG PRIMARY KEY,
	TenNNH NVARCHAR(30) NOT NULL,
	DiaChiNNH NVARCHAR(30) NOT NULL,
	SDTNNH CHAR(10) CONSTRAINT CK_SDTNNH CHECK(LEN(SDTNNH) = 10 AND ISNUMERIC(SDTNNH) = 1),
);

CREATE TABLE KEHANG
(
	MaKH CHAR(20) CONSTRAINT PK_KEHANG PRIMARY KEY,
	SucChua FLOAT CONSTRAINT CK_SucChua CHECK(SucChua > 0),
	ViTri NVARCHAR(30) NOT NULL,
	MaHH CHAR(20) NOT NULL
);

CREATE TABLE DANHMUC
(
	MaDM CHAR(20) CONSTRAINT PK_DANHMUC PRIMARY KEY,
	TenDM NVARCHAR(30) NOT NULL,
	MaHH CHAR(20) NOT NULL
);

CREATE TABLE NHAPHANG
(
	SoHD CHAR(20) NOT NULL,
	MaHH CHAR(20) NOT NULL,
	MaNPP CHAR(20) NOT NULL, 
	MaNNH CHAR(20) NOT NULL,
	CONSTRAINT PK_NHAPHANG PRIMARY KEY (SoHD, MaHH, MaNPP, MaNNH),
	NgayGio DATE CONSTRAINT CK_NgayGio CHECK(NgayGio <= GETDATE()),
	SoLuong INT CONSTRAINT CK_SoLuong CHECK(SoLuong >= 1),
	NVBH NVARCHAR(30) NOT NULL,
	NVGH NVARCHAR(30) NOT NULL,
	VAT FLOAT,
	TienCK FLOAT CONSTRAINT CK_TienCK CHECK(TienCK >= 0),
	ThanhTien FLOAT CONSTRAINT CK_ThanhTien CHECK(ThanhTien > 0),
	TongTien FLOAT CONSTRAINT CK_TongTien CHECK(TongTien > 0)
);

ALTER TABLE HANGHOA ADD 
	CONSTRAINT FK_HANGHOA_KEHANG FOREIGN KEY(MaKH) REFERENCES KEHANG(MaKH),
	CONSTRAINT FK_HANGHOA_DANHMUC FOREIGN KEY(MaDM) REFERENCES DANHMUC(MaDM)

ALTER TABLE KEHANG ADD CONSTRAINT FK_KEHANG_HANGHOA FOREIGN KEY(MaHH) REFERENCES HANGHOA(MaHH)

ALTER TABLE DANHMUC ADD CONSTRAINT FK_DANHMUC_HANGHOA FOREIGN KEY(MaHH) REFERENCES HANGHOA(MaHH)

ALTER TABLE NHAPHANG ADD 
	CONSTRAINT FK_NHAPHANG_HANGHOA FOREIGN KEY(MaHH) REFERENCES HANGHOA(MaHH),
	CONSTRAINT FK_NHAPHANG_NHAPHANPHOI FOREIGN KEY(MaNPP) REFERENCES NHAPHANPHOI(MaNPP),
	CONSTRAINT FK_NHAPHANG_NGUOINHANHANG FOREIGN KEY(MaNNH) REFERENCES NGUOINHANHANG(MaNNH)