CREATE DATABASE BTL

USE BTL

CREATE TABLE HANGHOA
(
	MAHH CHAR(20) CONSTRAINT PK_HANGHOA PRIMARY KEY,
	TENHH NVARCHAR(50),
	DVT NVARCHAR(20),
	DGN FLOAT CONSTRAINT CK_DGN CHECK(DGN >= 0),
	DGB FLOAT CONSTRAINT CK_DGB CHECK(DGB >= 0),
	MADM CHAR(20)
);

CREATE TABLE NHAPHANPHOI
(
	MANPP CHAR(20) CONSTRAINT PK_NHAPHANPHOI PRIMARY KEY,
	TENNPP NVARCHAR(50),
	DIACHINPP NVARCHAR(50),
	SDTNPP CHAR(10) CONSTRAINT CK_SDTNPP CHECK(LEN(SDTNPP) BETWEEN 9 AND 10 AND ISNUMERIC(SDTNPP) = 1)
);

CREATE TABLE NGUOINHANHANG
(
	MANNH CHAR(20) CONSTRAINT PK_NGUOINHANHANG PRIMARY KEY,
	TENNNH NVARCHAR(50),
	DIACHINNH NVARCHAR(50),
	SDTNNH CHAR(10) CONSTRAINT CK_SDTNNH CHECK(LEN(SDTNNH) BETWEEN 9 AND 10 AND ISNUMERIC(SDTNNH) = 1),
);

CREATE TABLE KEHANG
(
	MAKH CHAR(20) CONSTRAINT PK_KEHANG PRIMARY KEY,
	SUCCHUA FLOAT CONSTRAINT CK_SUCCHUA CHECK(SUCCHUA > 0),
	TANG NVARCHAR(30),
	MAHH CHAR(20) CONSTRAINT FK_KEHANG_HANGHOA FOREIGN KEY REFERENCES HANGHOA(MAHH)
);

CREATE TABLE DANHMUC
(
	MADM CHAR(20) CONSTRAINT PK_DANHMUC PRIMARY KEY,
	TENDM NVARCHAR(30),
);

CREATE TABLE NHAPHANG
(
	SOHD CHAR(20) NOT NULL,
	MAHH CHAR(20) NOT NULL,
	MANPP CHAR(20) NOT NULL, 
	MANNH CHAR(20) NOT NULL,
	CONSTRAINT PK_NHAPHANG PRIMARY KEY (SOHD, MAHH, MANPP, MANNH),
	NGAYGIO DATE CONSTRAINT CK_NGAYGIO CHECK(NGAYGIO <= GETDATE()),
	SOLUONG INT CONSTRAINT CK_SOLUONG CHECK(SOLUONG >= 1),
	NVBH NVARCHAR(30),
	NVGH NVARCHAR(30),
	VAT FLOAT,
	TIENCK MONEY CONSTRAINT CK_TIENCK CHECK(TIENCK >= 0),
	THANHTIEN MONEY CONSTRAINT CK_THANHTIEN CHECK(THANHTIEN >= 0),
	TONGTIEN MONEY CONSTRAINT CK_TONGTIEN CHECK(TONGTIEN >= 0)
);

ALTER TABLE HANGHOA ADD 
	CONSTRAINT FK_HANGHOA_DANHMUC FOREIGN KEY(MADM) REFERENCES DANHMUC(MADM)

ALTER TABLE NHAPHANG ADD 
	CONSTRAINT FK_NHAPHANG_HANGHOA FOREIGN KEY(MAHH) REFERENCES HANGHOA(MAHH),
	CONSTRAINT FK_NHAPHANG_NHAPHANPHOI FOREIGN KEY(MANPP) REFERENCES NHAPHANPHOI(MANPP),
	CONSTRAINT FK_NHAPHANG_NGUOINHANHANG FOREIGN KEY(MANNH) REFERENCES NGUOINHANHANG(MANNH)

SELECT * FROM HANGHOA
SELECT * FROM NHAPHANPHOI
SELECT * FROM NGUOINHANHANG
SELECT * FROM KEHANG
SELECT * FROM DANHMUC
SELECT * FROM NHAPHANG

INSERT INTO DANHMUC (MADM, TENDM)
VALUES
	('DM0001', N'ĐỒ ĂN'),
	('DM0002', N'ĐỒ UỐNG'),
	('DM0003', N'ĐỒ DÙNG CÁ NHÂN'),
	('DM0004', N'NHU YẾU PHẨM')


INSERT INTO KEHANG(MAKH, SUCCHUA, VITRI)
VALUES 
	(


INSERT INTO HANGHOA(MAHH, TENHH, DVT, DGN, DGB, MAKH, MADM)
VALUES
	(



INSERT INTO NHAPHANPHOI(MANPP, TENNPP, DIACHINPP, SDTNPP)
VALUES
	(

INSERT INTO NGUOINHANHANG(MANNH, TENNNH, DIACHINNH, SDTNNH)
VALUES 
	(

INSERT INTO NHAPHANG(SOHD, MAHH, MANPP, MANNH, NGAYGIO, SOLUONG, NVBH, NVGH, VAT, TIENCK, THANHTIEN, TONGTIEN)
VALUES
	(